{
 "title": "K6 Tests",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "I/O Byte Count - K6",
   "type": "stat",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "expr": "k6_data_received_bytes_total", "legendFormat": "__auto" },
    {
     "expr": "group by(__name__) (k6_data_sent_bytes_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Failed Ocurred - K6",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "k6_http_req_failed_occurred_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success Request Count - K6",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "k6_http_reqs_total{name=\"http://api:8000/forms\", status=\"200\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "k6_http_reqs_total{name=\"http://api:8000/forms/new\", status=\"200\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "k6_http_reqs_total{name=\"http://api:8000/forms/delete\", status=\"200\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "k6_http_reqs_total{name=\"http://api:8000/forms/update\", status=\"200\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VUs Count - K6",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "targets": [
    { "expr": "k6_vus", "legendFormat": "__auto" }
   ]
  }
 ]
}