{
 "title": "K6 Tests",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "I/O Byte Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "expr": "k6_data_received_bytes_total", "legendFormat": "__auto" },
    {
     "expr": "group by(__name__) (k6_data_sent_bytes_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Failed Ocurred",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "k6_http_req_failed_occurred_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "k6_http_reqs_total{expected_response=\"true\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}